### ISSUE TITLE
difference between a random instance and a random stub

### ISSUE THREAD

**Issue by beluchin** [eXparity/exparity-stub#11]
what's the difference between a random instance versus a random stub?

That is:
`Person aPerson = RandomBuilder.aRandomInstanceOf(Person.class);`

vs.
`Person aPerson = StubBuilder.aRandomStubOf(Person.class).build();`

Thanks

**Comment by stewbis** [comment]
Hi beluchin,

Depending on the use case there can be no difference and a huge difference between the behaviour. 

RandomBuilder.aRandomInstanceOf will attempt to set all Java bean properties on the Person class throughout the graph whereas RandomBuilder.aRandomStubOf (an alias on RandomBuilder which delegates to StubBuilder) will return a random value when any property on the  person is called.

If using in a test case where you want to use a stub just to return a random value when any method is called then either is suitable.

If you want to test marshalling, persistence, or other similar operations on a randomly populated instance then you'll want the stub produced by RandomBuilder.aRandomInstanceOf because it will return you a fully populate instance of Person with actual properties set.

If using it to create a random stub of an interface, a non-bean class, or a class populated primarily via constructor args then RandomBuilder.aRandomStubOf is the only option.

I hope that's answered your question - if not I'm happy to elaborate more.

Regards

Stewart
